### PR TITLE
add DP0.1 vs DP0.2 comparison notebook in new directory

### PR DESCRIPTION
**Pull request by rmandelb**
Adding new notebook comparing DP0.1 and DP0.2 object catalogs.

@MelissaGraham - I wanted to check whether the attribution at the top is sufficient:

> Attribution: the elements of this notebook that involve learning how to query the object catalogs are heavily based on [one of the DP0.2 tutorials](https://github.com/rubin-dp0/tutorial-notebooks/blob/main/02_Catalog_Queries_with_TAP.ipynb). Much of the explanatory text in the early parts of the notebook, before the comparison of DP0.1 and DP0.2 outputs, comes from there.

Is that OK or should I omit text that comes directly from those tutorials?

### CODE REVIEW

**Comment by rmandelb** [comment]
Hi @ztq1996 - I've requested a review from you - you can find this repo's review standards [here](https://github.com/rubin-dp0/delegate-contributions-dp02#reviews) (you don't have to do a full code review, just sanity check a few things).

**Comment by MelissaGraham** [comment]
> 

That attribution statement looks absolutely OK! 👍

**Review by MelissaGraham — APPROVED** [review]

**Comment by rmandelb** [comment]
Thank you for confirming!

What is the workflow in this repo - is one approving review sufficient to merge?

**Comment by MelissaGraham** [comment]
> Thank you for confirming!
> 
> What is the workflow in this repo - is one approving review sufficient to merge?

Yes, one reviewer is (should be) sufficient. It looks to me like this PR could be merged (the button is green) even without the second reviewer's approval? (I might have special permissions though).

**Comment by rmandelb** [comment]
Yes, it can.  Just wasn't sure if there was any behavioral norm I was missing.  Thanks!

**Pull request merged**
