### PR TITLE
Add Example DIA with proper motion

### PR DESCRIPTION
**Pull request by wmwv**
Adds a notebook that demonstrated injecting a moving star over a set of DC2 images and then run subtractions and detects and measures the sources on the difference image to determine the values for the dipole-related difference image measurements.

### CODE REVIEW

**Comment by wmwv** [comment]
I'd like to solicit @leeskelvin input here, but somehow can't add him as a reviewer.

**Review by MelissaGraham — APPROVED** [review]
Thanks for this contribution @wmwv  -- can you add a README to your new directory before you merge please, like in the example directory? https://github.com/rubin-dp0/delegate-contributions-dp02/tree/main/example

For this repo, the review stage is only to make sure people are not accidentally changing other people's files (b/c not everyone is familiar with git or GitHub), so please note that I have not reviewed the contents of your notebook. I only confirmed that it is the only file being changed. I noticed that you wanted Lee to look at it -- you can still request that, but separately from the PR, and then merge whenever you're ready.

Let me know if you'd like to present this in an upcoming Delegate Assembly. You might also like to share an announcement about this new resource in the Data Preview 0 category in the Forum (Community.lsst.org), after you merge.

**Comment by wmwv** [comment]
@MelissaGraham Should I move this DIA dipole proper motion notebook into `dia_exploration`?  Maybe it's not useful to have an additional subdirectory.

**Comment by MelissaGraham** [comment]
I suppose... keeping directory structures flatter in cases like this helps discoverability, so knowing nothing else I'd say yes to moving.

**Comment by MelissaGraham** [comment]
Oh sorry I misunderstood. I thought you had made sub-directories in your own new one. 
Either way, contribute to dia_expolration or keep separate, both ok

**Pull request merged**
